#!/usr/bin/env bash
# Bootstrap rmb on a clean Linux server (Ubuntu 22.04+/Debian 12+).
#
# From a git checkout on the server:
#   sudo ./scripts/install.sh
#
# Non-interactive (set secrets before running):
#   RMB_DOMAIN=memory.example.com \
#   RMB_LLM_API_KEY=sk-... \
#   RMB_EMBED_API_KEY=sk-... \
#   sudo -E ./scripts/install.sh
#
# Installs Docker if missing, writes deploy/.env + Caddyfile, builds the image,
# and starts PostgreSQL + rmb + Caddy (deploy/docker-compose.full.yml).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_DIR="${RMB_INSTALL_DIR:-$ROOT/deploy}"
COMPOSE_FILE="${RMB_COMPOSE_FILE:-$ROOT/deploy/docker-compose.full.yml}"
ENV_FILE="${DEPLOY_DIR}/.env"
CADDY_FILE="${DEPLOY_DIR}/config/Caddyfile"
CADDY_EXAMPLE="${DEPLOY_DIR}/config/Caddyfile.example"

log() { printf '==> %s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

need_root() {
  if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
    die "run as root (sudo ./scripts/install.sh)"
  fi
}

rand_secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '/+=' | head -c 24
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

prompt() {
  local var="$1" prompt="$2" default="${3:-}"
  if [[ -n "${!var:-}" ]]; then
    return 0
  fi
  if [[ ! -t 0 ]]; then
    die "set ${var} for non-interactive install"
  fi
  if [[ -n "$default" ]]; then
    read -r -p "${prompt} [${default}]: " val
    printf -v "$var" '%s' "${val:-$default}"
  else
    read -r -p "${prompt}: " val
    printf -v "$var" '%s' "$val"
  fi
  if [[ -z "${!var}" ]]; then
    die "${var} is required"
  fi
}

ensure_docker() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    log "docker and compose plugin present"
    return 0
  fi
  if [[ "${SKIP_DOCKER_INSTALL:-}" == "1" ]]; then
    die "docker not found and SKIP_DOCKER_INSTALL=1"
  fi
  log "installing Docker (get.docker.com)"
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
}

write_env() {
  prompt RMB_DOMAIN "Public domain (DNS A/AAAA → this host)"
  prompt RMB_LLM_API_BASE "Chat API base URL" "https://api.openai.com/v1"
  prompt RMB_LLM_API_KEY "Chat API key"
  prompt RMB_LLM_MODEL "Chat model" "gpt-4o-mini"
  prompt RMB_EMBED_API_BASE "Embedding API base URL" "${RMB_LLM_API_BASE}"
  prompt RMB_EMBED_API_KEY "Embedding API key" "${RMB_LLM_API_KEY}"
  prompt RMB_EMBED_MODEL "Embedding model" "text-embedding-3-small"
  prompt RMB_EMBED_DIMENSIONS "Embedding dimensions" "1536"

  POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(rand_secret)}"
  USERNAME="${RMB_ADMIN_USERNAME:-${USERNAME:-rmb}}"
  PASSWORD="${RMB_ADMIN_PASSWORD:-${PASSWORD:-$(rand_secret)}}"

  mkdir -p "$DEPLOY_DIR"
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date -u +%Y-%m-%dT%H:%MZ)
RMB_DOMAIN=${RMB_DOMAIN}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
USERNAME=${USERNAME}
PASSWORD=${PASSWORD}
RMB_LLM_PROVIDER=openai
RMB_LLM_API_BASE=${RMB_LLM_API_BASE}
RMB_LLM_API_KEY=${RMB_LLM_API_KEY}
RMB_LLM_MODEL=${RMB_LLM_MODEL}
RMB_LLM_MAX_RETRIES=3
RMB_LLM_TIMEOUT=180s
RMB_LLM_THINKING_STYLE=
RMB_LLM_THINKING=disabled
RMB_EMBED_ENABLED=true
RMB_EMBED_API_BASE=${RMB_EMBED_API_BASE}
RMB_EMBED_API_KEY=${RMB_EMBED_API_KEY}
RMB_EMBED_MODEL=${RMB_EMBED_MODEL}
RMB_EMBED_DIMENSIONS=${RMB_EMBED_DIMENSIONS}
RMB_EMBED_POLL_INTERVAL=30s
RMB_EMBED_BATCH_SIZE=32
RMB_EXTRACTION_ENABLED=true
RMB_SCENE_ENABLED=true
RMB_MEMORY_ENABLED=true
EOF
  chmod 600 "$ENV_FILE"
  log "wrote ${ENV_FILE}"
}

write_caddyfile() {
  mkdir -p "${DEPLOY_DIR}/config"
  if [[ -f "$CADDY_EXAMPLE" ]]; then
    cp "$CADDY_EXAMPLE" "$CADDY_FILE"
  else
    cat >"$CADDY_FILE" <<'EOF'
{$RMB_DOMAIN} {
	reverse_proxy rmb:8080
}
EOF
  fi
  log "wrote ${CADDY_FILE}"
}

compose_up() {
  log "building and starting stack"
  # shellcheck disable=SC1090
  set -a && source "$ENV_FILE" && set +a
  export GIT_COMMIT="${GIT_COMMIT:-$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)}"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --build
}

wait_health() {
  log "waiting for rmb healthz (via Caddy → rmb)"
  local i
  for i in $(seq 1 40); do
    if docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" exec -T rmb \
      wget -q -O- http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
      log "healthz OK"
      return 0
    fi
    sleep 3
  done
  die "healthz failed — check: docker compose -f ${COMPOSE_FILE} logs rmb"
}

print_summary() {
  # shellcheck disable=SC1090
  set -a && source "$ENV_FILE" && set +a
  cat <<EOF

rmb is running.

  URL:      https://${RMB_DOMAIN}
  UI:       https://${RMB_DOMAIN}/ui/
  Health:   https://${RMB_DOMAIN}/healthz

  HTTP auth user: ${USERNAME}
  HTTP auth pass: ${PASSWORD}

Client config (~/.rmb.conf on your laptop):

  RMB_URL=https://${RMB_DOMAIN}
  RMB_USERNAME=${USERNAME}
  RMB_PASSWORD=${PASSWORD}

Hook example:

  /path/to/rmb hook-submit --source=cursor

Logs:

  cd ${DEPLOY_DIR%/*} && docker compose -f ${COMPOSE_FILE} logs -f rmb

EOF
}

main() {
  need_root
  [[ -f "$COMPOSE_FILE" ]] || die "compose file not found: $COMPOSE_FILE (run from git checkout)"
  ensure_docker
  write_env
  write_caddyfile
  compose_up
  wait_health
  print_summary
}

main "$@"
